# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Code\AiAudio\app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.setEnabled(True)
        Form.resize(400, 100)
        Form.setMinimumSize(QtCore.QSize(400, 100))
        Form.setMaximumSize(QtCore.QSize(400, 100))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(5, 20, 391, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.CBSpeaker = QtWidgets.QComboBox(self.widget)
        self.CBSpeaker.setObjectName("CBSpeaker")
        self.horizontalLayout.addWidget(self.CBSpeaker)
        self.BtnListen = QtWidgets.QPushButton(self.widget)
        self.BtnListen.setObjectName("BtnListen")
        self.horizontalLayout.addWidget(self.BtnListen)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "一个小煞笔"))
        self.label.setText(_translate("Form", "TTS+ChatGPT+STT"))
        self.BtnListen.setText(_translate("Form", "Listen"))
