# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Code\AiAudio\ui\app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.setEnabled(True)
        Form.resize(400, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(400, 200))
        Form.setMaximumSize(QtCore.QSize(400, 200))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(9, 10, 381, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lb_status = QtWidgets.QLabel(Form)
        self.lb_status.setGeometry(QtCore.QRect(10, 170, 381, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(8)
        self.lb_status.setFont(font)
        self.lb_status.setStyleSheet("color: rgb(255, 0, 0);")
        self.lb_status.setTextFormat(QtCore.Qt.PlainText)
        self.lb_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_status.setObjectName("lb_status")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(50, 50, 291, 111))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.cb_speaker = QtWidgets.QComboBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.cb_speaker.setFont(font)
        self.cb_speaker.setObjectName("cb_speaker")
        self.cb_decoder = QtWidgets.QComboBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.cb_decoder.setFont(font)
        self.cb_decoder.setObjectName("cb_decoder")
        self.btn_load = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.btn_load.setFont(font)
        self.btn_load.setObjectName("btn_load")
        self.btn_listen = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.btn_listen.setFont(font)
        self.btn_listen.setStyleSheet("")
        self.btn_listen.setObjectName("btn_listen")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "一个小煞笔"))
        self.label.setText(_translate("Form", "TTS+ChatGPT+STT"))
        self.lb_status.setText(_translate("Form", "TextLabel"))
        self.btn_load.setText(_translate("Form", "Load Model"))
        self.btn_listen.setText(_translate("Form", "Listen"))
